#!/bin/bash -e
set -o pipefail

source "$(dirname "${BASH_SOURCE[0]}")/common.inc"

commit_file="$1"

cleanup() {
	[[ ! -e "$commit_file_tmp" ]] || rm "$commit_file_tmp"
}
trap cleanup EXIT

[[ $commit_file != "" ]]

commit_file_tmp=$( mktemp )
if egrep -v '^#' "$commit_file" > "$commit_file_tmp" ; then
	# (can't use a ! in the if or the return code is wiped)
	:
else
	if [[ $? -eq 1 ]] ; then
		fail "Empty commits are not allowed"
	else
		fail "Error reading commit message"
	fi
fi

if ! head -n 1 "$commit_file_tmp" | egrep "$commit_msg_regex" >/dev/null ; then
	fail "First line of commit message does not match conventions"
fi

if [[ $( wc -l < "$commit_file_tmp" ) -gt 2 ]] ; then
	if ! head -n 2 "$commit_file_tmp" | tail -n 1 | egrep '^$' ; then
		fail "Second line of commit message should be blank"
	fi
fi

