# Generated by Django 2.2.9 on 2020-01-14 23:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("xenopus_frog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                blank=True,
                choices=[
                    [1, "One"],
                    [2, "OneOne"],
                    [3, "OneOneOne"],
                    [4, "OneOneOneOne"],
                ],
                null=True,
            ),
        ),
    ]
