# Generated by Django 2.2.9 on 2020-01-15 02:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("xenopus_frog", "0002_user_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.IntegerField(
                blank=True,
                choices=[
                    [1, "Oceania"],
                    [2, "Asia"],
                    [3, "Africa"],
                    [4, "America"],
                    [5, "Europe"],
                    [6, "Antarctica"],
                    [7, "Atlantis"],
                ],
                null=True,
            ),
        ),
    ]
